name: "[PROD] CI/CD Deploy"

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Execute deploy
    uses: ./.github/workflows/execute-deploy.yml
    with:
      environment: 'prod'
      github_environment: 'production'
    secrets:
      docker-user: ${{ secrets.DOCKER_USER }}
      docker-pass: ${{ secrets.DOCKER_PASS }}
      docker-repo: ${{ secrets.REPO_DOCKER }}
      github-token: ${{ secrets.GH_TOKEN }}
      vps-host: ${{ secrets.VPS_HOST }}
      vps-username: ${{ secrets.VPS_USERNAME }}
      vps-ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}